### ISSUE TITLE
Server Updated?

### ISSUE THREAD

**Issue by khildren** [ChillGenXer/sapiens-server#2]
Dude! thanks for the youtube video and install scripts - super rad.

I may be misunderstanding something, I run  ./sapiens.sh upgrade and i get this added bit in there. 

2024-07-31 09:29:34 [INFO]: Checking for Sapiens Dedicated Server updates
**ln: failed to create symbolic link '/home/sapserver/.steam/root': No such file or directory
ln: failed to create symbolic link '/home/sapserver/.steam/steam': No such file or directory**
Redirecting stderr to '/home/sapserver/Steam/logs/stderr.txt'
Logging directory: '/home/sapserver/Steam/logs'
[  0%] Checking for available updates...
[----] Verifying installation...
UpdateUI: skip show logoSteam Console Client (c) Valve Corporation - version 1721172922
-- type 'quit' to exit --
Loading Steam API...OK

Connecting anonymously to Steam Public...OK
Waiting for client config...OK
Waiting for user info...OK
 Update state (0x5) verifying install, progress: 0.44 (1048576 / 237314738)
Success! App '2886350' fully installed.

It runs, but did not grab update

![image](https://github.com/user-attachments/assets/95278b49-6530-45c2-9720-6533d1ab6af9)

was rocking well until this update

**Comment by ChillGenXer** [comment]
I've been super busy with real life and haven't been able to sit down at my computer for 2 weeks!  This is because the scripts are not updated now that you can run the beta versions.  If you want to fix it yourself before I commit the change you can change this function in **manage_server.sh** to include the new **-beta** flag:

upgrade_server() {
    logit "INFO" "Checking for Sapiens Dedicated Server updates" "echo"
    steamcmd +force_install_dir sapiens +login anonymous +app_update 2886350 -beta public-beta-unstable validate +quit
}

**Comment by khildren** [comment]
thank you, my dude! Your scripts are appreciated :)
